name: shmr_hw
description: "A homework project for shmr"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  auto_route: ^10.1.0+1
  bloc: ^9.0.0
  collection: ^1.19.1
  cupertino_icons: ^1.0.8
  decimal: ^3.2.1
  drift: ^2.27.0
  drift_flutter: ^0.2.4
  easy_localization: ^3.0.7+1
  fl_chart: ^1.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_colorpicker: ^1.1.0
  flutter_dotenv: ^5.2.1
  flutter_native_splash: ^2.4.6
  flutter_secure_storage: ^4.2.1
  freezed_annotation: ^3.0.0
  fuzzywuzzy: ^1.2.0
  http: ^1.4.0
  json_annotation: ^4.9.0
  local_auth: ^2.3.0
  path_provider: ^2.1.5
  sensors_plus: ^6.1.1
  shared_preferences: ^2.5.3
  shmr_hw_pie_chart:
    path: ./shmr_hw_pie_chart
  skeletonizer: ^2.0.1
  worker_manager: ^7.2.6

dev_dependencies:
  auto_route_generator: ^10.2.3
  bloc_lint: ^0.2.0-dev.6
  build_runner: ^2.5.4
  custom_lint: ^0.7.5
  drift_dev: ^2.27.0
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  json_serializable: ^6.9.0
  sp_lints:
    git: https://git.selfprivacy.org/SelfPrivacy/sp-lints.git

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - .env
  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf

flutter_native_splash:
  color: "#6AA379"

  image: assets/icons/png/account.png

  android_12:
    color: "#6AA379"
    icon_background_color: "#6AA379"
