name: shmr_hw
description: "A homework project for shmr"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  auto_route: ^10.1.0+1
  bloc: ^9.0.0
  cupertino_icons: ^1.0.8
  decimal: ^3.2.1
  easy_localization: ^3.0.7+1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  freezed_annotation: ^3.0.0
  gap: ^3.0.1
  json_annotation: ^4.9.0

dev_dependencies:
  auto_route_generator: ^10.2.3
  bloc_lint: ^0.2.0-dev.6
  build_runner: ^2.4.15
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf

